FROM debian

RUN 	apt update \
&&	apt install -y \
	bash sudo

RUN	useradd -m -s /bin/bash vd \
&&	echo "vd:p" | chpasswd \
&&	usermod -aG sudo vd \
&&	echo "vd ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/vd

RUN	apt install -y \
	neofetch tmux tightvncserver xfce4 xfce4-terminal dbus-x11 xsel \
        firefox-esr \
	openssh-server openssl rsync locales \
	git curl vim \
	\
	gcc libc6-dev \
	rsync \
	python3 python3-pip \
	lua5.4 luarocks

RUN	echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

USER vd
WORKDIR /home/vd

RUN	sudo luarocks install luafilesystem

RUN 	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash \
&&	export NVM_DIR="$HOME/.nvm" \
&&	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
&&	nvm install node \
&&	node --version && npm --version \
&&	npm install -g \
	esbuild typescript \
	http-server live-server \

RUN	curl -fsSL https://bun.sh/install | bash

RUN	curl -fLo /home/vd/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
&&	mkdir -p ~/.vim/pack/airblade/start \
&&	cd ~/.vim/pack/airblade/start \
&&	git clone https://github.com/airblade/vim-gitgutter.git \
&&	vim -u NONE -c "helptags vim-gitgutter/doc" -c q

RUN	git clone https://github.com/tmux-plugins/tpm /home/vd/.tmux/plugins/tpm \
&&	git clone https://github.com/marlon-erler/setup /home/vd/A \
&&	ls /home/vd

RUN	echo "=== RUNNING SETUP ===" \
&&	ls /home/vd/A/scripts \
&&	/home/vd/A/scripts/setup \
&&	export BAK=/home/vd/A/backups \
&&	/home/vd/A/scripts/backup restore

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

USER root

RUN	export INSTALL=/home/vd/A/installers \
&&	/home/vd/A/scripts/install-local

USER vd
ENV USER vd

RUN rm -rf /home/vd/.config/chromium
