FROM debian

RUN 	apt update \
&&	apt install -y \
	bash sudo

RUN	useradd -m -s /bin/bash vd \
&&	echo "vd:p" | chpasswd \
&&	usermod -aG sudo vd \
&&	echo "vd ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/vd

RUN	apt install -y \
	tmux tightvncserver xfce4 xfce4-terminal dbus-x11 xsel \
        firefox-esr \
	openssh-server openssl rsync locales \
	git curl vim \
	\
	gcc libc6-dev \
	nodejs npm \
	rsync \
	python3 python3-pip \
	lua5.4 luarocks \
	\
	\
&&	npm install -g \
	esbuild \
	http-server live-server \
	\
	\
&&	sudo luarocks install luafilesystem

RUN	echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

USER vd
WORKDIR /home/vd

RUN	curl -fsSL https://bun.sh/install | bash \
	\
	\
&&	curl -fLo /home/vd/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim


RUN	git clone https://github.com/tmux-plugins/tpm /home/vd/.tmux/plugins/tpm \
&&	git clone https://github.com/marlon-erler/setup /home/vd/A \
&&	ls /home/vd

RUN	echo "=== RUNNING SETUP ===" \
&&	ls /home/vd/A/scripts \
&&	/home/vd/A/scripts/setup \
&&	export BAK=/home/vd/A/backups \
&&	/home/vd/A/scripts/backup restore

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

USER root

RUN	export INSTALL=/home/vd/A/installers \
&&	/home/vd/A/scripts/install-local

USER vd
ENV USER vd

RUN rm -rf /home/vd/.config/chromium
