#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

infile=$1
outfile=$2

guard "$infile" "infile not specified"
guard "$outfile" "outfile not specified"

tmp=/tmp/catstart-temp

cat $outfile > $tmp
cat $infile > $outfile
cat $tmp >> $outfile
