#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

mkdir -p \
    $CODE/Arduino \
    $CODE/OMN \
    $CODE/Junk

cd $CODE/Arduino
git clone git@github.com:marlon-erler/LED-Strip.git

cd $CODE/OMN
git clone git@github.com:OpenMessagingNetwork/.github.wiki wiki

cd $CODE/Junk
git clone git@github.com:marlon-erler/ganzflicker.git
