#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

name=$1
guard "$name" "username not specified"
msg=$2
guard "$msg" "message not specified"

hostcmd $name "echo \"$msg\" | pbcopy"
