#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

cmd=$1
guard "$cmd" "command not specified"

apt_packages=$(pac-config ls apt)
bun_packages=$(pac-config ls bun)
lua_packages=$(pac-config ls lua)

install() {
    for package in $1; do
	echo "installing $package..."
	command ${@:2} $package
	echo "---"
    done
}

case $cmd in
    apt)
	install "$apt_packages" sudo apt install -y
	;;

    bun)
	install "$bun_packages" bun add -g
	;;

    lua)
	install "$lua_packages" sudo luarocks install
	;;

    other)
	curl -fsSL https://install.julialang.org | sh
	curl -fsSL https://bun.sh/install | bash

	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	;;

    *)
	echo "unknown command"
esac
