#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

cat ~/A/assets/bashrc >> ~/.bashrc

git config --global user.name marlon-erler
git config --global user.email viridian035@gmail.com

ssh-keygen
