#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

layout=$1
guard "$layout" "layout not specified"

case $layout in
    dev)
	tmux split-pane
	tmux select-pane -t 1
	tmux resize-pane -y 10
	tmux split-pane -h
	tmux select-pane -t 0
	sleep 0.5
	tmux send-keys -t 0 'vimm' Enter
	;;

    *)
	echo "unknown layout"
esac
