#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

### 0
tmux-session 0

### VAULT
tmux-session 01-MAIN "
    $A
    $A/podman/alpine
    $A/podman/debian
    $BAK
    $SCRIPTS
    $ASSETS"

### CODE LAB
lab=$CODE/Lab
tmux-session 02-CODE-LAB "
    $lab/Julia
    $lab/Lua
    $lab/R"

### OMN
omn=$CODE/OMN
tmux-session 03-OMN "
    $omn/wiki"

### LED
tmux-session 04-LED "
    $CODE/LED-Strip"

### FUNDAMENT
fundament=$CODE/Fundament
tmux-session 05-FUNDAMENT "
    $fundament/template
    $fundament/themes
    $fundament/components
    $fundament/reactivity"

### FINISH
cd
tmux attach -t 01-MAIN
